"""Enhanced AI content detection metrics for v6.

ImagePixelAnalysis: analyze actual image pixels for AI artifacts
DeepfakeTextDetector: enhanced text detection with more signals
"""

from __future__ import annotations

import math
import re
import sys

from llmevalkit.models import MetricResult
from llmevalkit.detection import _type_token_ratio, _burstiness, _repetition_score, _transition_score, _perplexity_proxy, _sentence_lengths


class ImagePixelAnalysis:
    """Analyze image file for AI generation artifacts.

    Accepts image file path or base64. Checks:
    - Color distribution uniformity (AI images often have uniform noise)
    - JPEG compression artifacts (real photos have them, AI often doesn't)
    - Metadata completeness
    """
    name = "image_pixel_analysis"

    def __init__(self, use_llm=False, weight=1.0):
        self.use_llm = use_llm
        self.weight = weight

    @property
    def required_fields(self):
        return ["answer"]

    def validate_inputs(self, **kwargs):
        return bool(kwargs.get("answer"))

    def evaluate(self, client=None, **kwargs):
        answer = kwargs.get("answer", "")

        if not answer:
            return MetricResult(name=self.name, score=0.5, reason="No image data")

        signals = []

        # Try to load image if it's a file path
        try:
            from PIL import Image
            import numpy as np

            img = None
            if isinstance(answer, str) and len(answer) < 500:
                import os
                if os.path.exists(answer):
                    img = Image.open(answer)

            if img is not None:
                arr = np.array(img)

                # Check color distribution uniformity
                if len(arr.shape) >= 3:
                    for ch in range(min(3, arr.shape[2])):
                        std = float(np.std(arr[:, :, ch]))
                        if std < 20:
                            signals.append({"signal": "low_color_variance_ch{}".format(ch), "value": round(std, 1), "indicates": "possibly_ai"})

                # Check noise pattern
                if len(arr.shape) >= 2:
                    # Simple edge detection variance
                    gray = np.mean(arr, axis=2) if len(arr.shape) == 3 else arr
                    dx = np.diff(gray, axis=1)
                    noise_std = float(np.std(dx))
                    if noise_std < 5:
                        signals.append({"signal": "uniform_noise", "value": round(noise_std, 2), "indicates": "possibly_ai"})
                    elif noise_std > 50:
                        signals.append({"signal": "high_noise_variance", "value": round(noise_std, 2), "indicates": "likely_real"})

                # Check resolution
                w, h = img.size
                if w == h and w in [256, 512, 1024, 2048, 4096]:
                    signals.append({"signal": "square_power_of_2", "value": "{}x{}".format(w, h), "indicates": "possibly_ai"})

                # Check EXIF
                exif = img.getexif() if hasattr(img, 'getexif') else {}
                if not exif:
                    signals.append({"signal": "no_exif_data", "indicates": "possibly_ai"})
                else:
                    signals.append({"signal": "has_exif_data", "indicates": "likely_real"})

            else:
                # Fall back to text-based analysis (metadata description)
                return self._text_fallback(answer)

        except ImportError:
            return self._text_fallback(answer)
        except Exception as e:
            return self._text_fallback(answer)

        ai_signals = sum(1 for s in signals if s.get("indicates") == "possibly_ai")
        real_signals = sum(1 for s in signals if s.get("indicates") == "likely_real")

        if ai_signals > real_signals:
            score = max(0.0, 0.5 - ai_signals * 0.15)
            reason = "AI artifacts detected ({} signals)".format(ai_signals)
        elif real_signals > 0:
            score = min(1.0, 0.5 + real_signals * 0.2)
            reason = "Real image indicators found"
        else:
            score = 0.5
            reason = "Inconclusive"

        return MetricResult(name=self.name, score=round(score, 4), reason=reason,
                            details={"signals": signals, "ai_signals": ai_signals, "real_signals": real_signals})

    def _text_fallback(self, answer):
        """Fallback when PIL not available -- analyze metadata text."""
        answer_lower = answer.lower()
        ai_tools = ['dall-e', 'midjourney', 'stable diffusion', 'ai generated',
                     'leonardo', 'firefly', 'ideogram', 'flux', 'generated by']
        camera_markers = ['canon', 'nikon', 'sony', 'fuji', 'iphone', 'samsung',
                          'pixel', 'exposure', 'f/', 'iso', 'focal length']

        ai_found = [t for t in ai_tools if t in answer_lower]
        camera_found = any(m in answer_lower for m in camera_markers)

        if ai_found:
            return MetricResult(name=self.name, score=0.0, reason="AI tool markers: " + ", ".join(ai_found),
                                details={"method": "text_fallback", "ai_markers": ai_found})
        if camera_found:
            return MetricResult(name=self.name, score=1.0, reason="Camera metadata present",
                                details={"method": "text_fallback"})
        return MetricResult(name=self.name, score=0.5, reason="Inconclusive (text-only analysis)",
                            details={"method": "text_fallback"})


class DeepfakeTextDetector:
    """Enhanced AI text detection with additional signals beyond v5.

    Adds: paragraph structure analysis, punctuation diversity,
    hedging ratio, list usage, sentence start patterns.
    """
    name = "deepfake_text_detector"

    def __init__(self, use_llm=False, weight=1.0):
        self.use_llm = use_llm
        self.weight = weight

    @property
    def required_fields(self):
        return ["answer"]

    def validate_inputs(self, **kwargs):
        return bool(kwargs.get("answer")) and len(kwargs.get("answer", "").split()) >= 20

    def evaluate(self, client=None, **kwargs):
        answer = kwargs.get("answer", "")

        if not answer:
            return MetricResult(name=self.name, score=0.5, reason="Empty text")

        words = answer.split()
        if len(words) < 20:
            return MetricResult(name=self.name, score=0.5,
                                reason="Text too short (need 20+ words)")

        # Base signals from v5
        perplexity = _perplexity_proxy(answer)
        burstiness = _burstiness(answer)
        vocabulary = _type_token_ratio(answer)
        repetition = _repetition_score(answer)
        transition = _transition_score(answer)

        # NEW: Punctuation diversity
        punct_types = set(c for c in answer if c in '.,;:!?-()[]{}"\'/—–…')
        punct_diversity = min(1.0, len(punct_types) / 6.0)

        # NEW: Sentence start diversity
        sentences = re.split(r'(?<=[.!?])\s+', answer.strip())
        sentences = [s.strip() for s in sentences if s.strip()]
        if len(sentences) >= 3:
            starts = [s.split()[0].lower() if s.split() else '' for s in sentences]
            unique_starts = len(set(starts))
            start_diversity = unique_starts / len(starts)
        else:
            start_diversity = 0.5

        # NEW: Hedging ratio (humans hedge more naturally)
        hedging_words = ['maybe', 'perhaps', 'probably', 'might', 'could', 'seems',
                         'i think', 'i believe', 'not sure', 'kind of', 'sort of',
                         'honestly', 'actually', 'basically', 'literally']
        text_lower = answer.lower()
        hedge_count = sum(1 for h in hedging_words if h in text_lower)
        hedge_ratio = min(1.0, hedge_count / max(len(sentences), 1) * 3)

        # NEW: Paragraph structure (AI tends to write uniform paragraphs)
        paragraphs = [p.strip() for p in answer.split('\n\n') if p.strip()]
        if len(paragraphs) >= 2:
            para_lengths = [len(p.split()) for p in paragraphs]
            para_mean = sum(para_lengths) / len(para_lengths)
            para_var = sum((l - para_mean) ** 2 for l in para_lengths) / len(para_lengths)
            para_diversity = min(1.0, math.sqrt(para_var) / max(para_mean, 1) * 2)
        else:
            para_diversity = 0.5

        # Weighted combination
        score = (perplexity * 0.15 +
                 burstiness * 0.15 +
                 vocabulary * 0.10 +
                 repetition * 0.10 +
                 transition * 0.15 +
                 punct_diversity * 0.10 +
                 start_diversity * 0.10 +
                 hedge_ratio * 0.05 +
                 para_diversity * 0.10)

        signals = {
            "perplexity_proxy": round(perplexity, 3),
            "burstiness": round(burstiness, 3),
            "vocabulary_diversity": round(vocabulary, 3),
            "repetition": round(repetition, 3),
            "transition_uniformity": round(transition, 3),
            "punctuation_diversity": round(punct_diversity, 3),
            "sentence_start_diversity": round(start_diversity, 3),
            "hedging_ratio": round(hedge_ratio, 3),
            "paragraph_diversity": round(para_diversity, 3),
            "word_count": len(words),
        }

        if self.use_llm and client:
            try:
                prompt = "Analyze if this text is AI-generated or human.\n\nText:\n{}\n\nRespond JSON: {{\"human_score\": 0.5, \"reason\": \"...\"}}".format(answer[:1500])
                llm_result = client.generate_json(prompt, system="You are an AI content expert. JSON only.")
                llm_score = llm_result.get("human_score", 0.5)
                if isinstance(llm_score, str): llm_score = float(llm_score)
                score = score * 0.35 + llm_score * 0.65
                signals["llm_assessment"] = llm_result
            except Exception:
                pass

        if score >= 0.6:
            likely = "likely human"
        elif score >= 0.4:
            likely = "uncertain"
        else:
            likely = "likely AI-generated"

        return MetricResult(name=self.name, score=round(score, 4),
                            reason="{} (score: {:.2f}, 9 signals)".format(likely, score),
                            details=signals)
